USE spring_blog_db;


insert into posts (title, body) values ('non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 'Coqui partridge');
insert into posts (title, body) values ('pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam', 'Waterbuck, common');
insert into posts (title, body) values ('iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate', 'Ring-tailed possum');
insert into posts (title, body) values ('donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede', 'Tiger cat');
insert into posts (title, body) values ('vivamus tortor duis mattis egestas metus aenean fermentum donec ut', 'Squirrel, thirteen-lined');
insert into posts (title, body) values ('sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu', 'Brush-tailed bettong');
insert into posts (title, body) values ('nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat', 'Bandicoot, long-nosed');
insert into posts (title, body) values ('mi integer ac neque duis bibendum morbi non quam nec dui', 'Short-nosed bandicoot');
insert into posts (title, body) values ('libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh', 'Macaw, green-winged');
insert into posts (title, body) values ('ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 'Curlew, black');
insert into posts (title, body) values ('ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa', 'Mongoose, banded');
insert into posts (title, body) values ('fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', 'Snake, racer');
insert into posts (title, body) values ('eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 'Hyena, spotted');
insert into posts (title, body) values ('at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 'Silver-backed fox');
insert into posts (title, body) values ('volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse', 'Wombat, southern hairy-nosed');
insert into posts (title, body) values ('magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', 'Bee-eater, nubian');
insert into posts (title, body) values ('viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit', 'Brown pelican');
insert into posts (title, body) values ('dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum', 'Dragon, asian water');
insert into posts (title, body) values ('vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus', 'Cormorant, neotropic');
insert into posts (title, body) values ('viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui', 'Ostrich');
insert into posts (title, body) values ('dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 'Blue fox');
insert into posts (title, body) values ('tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', 'Stork, white-necked');
insert into posts (title, body) values ('ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum', 'Ibis, glossy');
insert into posts (title, body) values ('nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit', 'Hornbill, yellow-billed');
insert into posts (title, body) values ('ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 'Snake, western patch-nosed');
insert into posts (title, body) values ('sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 'Jackal, indian');
insert into posts (title, body) values ('justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'Cat, ringtail');
insert into posts (title, body) values ('rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at', 'Trumpeter swan');
insert into posts (title, body) values ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', 'Arctic ground squirrel');
insert into posts (title, body) values ('justo eu massa donec dapibus duis at velit eu est congue elementum in hac', 'Dik, kirk''s dik');
insert into posts (title, body) values ('amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo', 'Possum, western pygmy');
insert into posts (title, body) values ('id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel', 'Bare-faced go away bird');
insert into posts (title, body) values ('vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 'Grey-footed squirrel');
insert into posts (title, body) values ('felis eu sapien cursus vestibulum proin eu mi nulla ac', 'Stork, european');
insert into posts (title, body) values ('ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat', 'Malachite kingfisher');
insert into posts (title, body) values ('consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 'Ibis, glossy');
insert into posts (title, body) values ('amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis', 'Feral rock pigeon');
insert into posts (title, body) values ('convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien', 'Snow goose');
insert into posts (title, body) values ('condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', 'Gazelle, grant''s');
insert into posts (title, body) values ('potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', 'Butterfly (unidentified)');
insert into posts (title, body) values ('ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', 'Golden jackal');
insert into posts (title, body) values ('quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 'Suricate');
insert into posts (title, body) values ('nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere', 'Baleen whale');
insert into posts (title, body) values ('tempus vivamus in felis eu sapien cursus vestibulum proin eu', 'Boa, columbian rainbow');
insert into posts (title, body) values ('tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 'Porcupine, tree');
insert into posts (title, body) values ('faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', 'Asian water dragon');
insert into posts (title, body) values ('curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', 'Ocelot');
insert into posts (title, body) values ('quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in', 'Black-tailed deer');
insert into posts (title, body) values ('nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus', 'African ground squirrel (unidentified)');
insert into posts (title, body) values ('convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus', 'Bear, polar');